"""
Text-to-speech synthesis adapter using Kokoro TTS for natural Spanish voice.
Implements SpeechSynthesizer protocol and registers @tool methods.
"""

from __future__ import annotations

import asyncio
from datetime import datetime
import json
import logging
import os
import time
from typing import Annotated, Optional

from kokoro import KPipeline
import numpy as np
from pydub import AudioSegment
import soundfile as sf
from src.config.settings import SethSettings, get_settings
from src.infrastructure.tools.registry import tool

logger = logging.getLogger(__name__)


class KokoroSynthesizer:
    """Synthesizes Spanish audio from text using Kokoro KPipeline."""

    def __init__(self, settings: SethSettings | None = None, lang_code: str = "e", voice: str = "ef_dora") -> None:
        self.settings = settings or get_settings()
        self.lang_code = lang_code
        self.voice = voice
        self.storage_dir = str(self.settings.storage_audio_dir)
        os.makedirs(self.storage_dir, exist_ok=True)
        self._pipeline: Optional[KPipeline] = None
        self._lock = asyncio.Lock()
        logger.info("🔊 [SPEECH SYSTEM INIT] Kokoro configured for Spanish (voice: %s).", self.voice)

    def _init_tts(self) -> KPipeline:
        if self._pipeline is None:
            self._pipeline = KPipeline(lang_code=self.lang_code)
        return self._pipeline

    def _sync_generate_audio(self, text: str, wav_path: str, mp3_path: str) -> None:
        pipeline_engine = self._init_tts()
        generator = pipeline_engine(text, voice=self.voice, speed=1.0)

        audio_chunks = []
        sample_rate = 24000

        for _, _, audio in generator:
            audio_chunks.append(audio)

        if not audio_chunks:
            raise ValueError("No audio chunks generated by Kokoro.")

        final_audio = np.concatenate(audio_chunks)
        sf.write(wav_path, final_audio, sample_rate)
        AudioSegment.from_wav(wav_path).export(mp3_path, format="mp3")
        if os.path.exists(wav_path):
            os.remove(wav_path)

    async def synthesize(self, text: str) -> str:
        """Synthesizes text into an MP3 file asynchronously."""
        async with self._lock:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            base_filename = f"speech_{timestamp}_{int(time.time()) % 10000}"
            wav_path = os.path.join(self.storage_dir, f"{base_filename}.wav")
            mp3_path = os.path.join(self.storage_dir, f"{base_filename}.mp3")

            await asyncio.to_thread(self._sync_generate_audio, text, wav_path, mp3_path)
            return mp3_path

    @tool
    async def generate_speech(
        self,
        text: Annotated[str, (
            "The exact, clean conversational text to be synthesized into audio. "
            "CRITICAL: Must be pure text in Spanish without markdown, code blocks, or tags."
        )],
    ) -> str:
        """
        Use this tool ONLY when user explicitly asks you to speak, read aloud,
        or convert a message into voice/audio.
        """
        logger.info("🎙️ [KOKORO TTS] Generating speech for: '%s...'", text[:40])
        try:
            mp3_path = await self.synthesize(text)
            report = {
                "status": "success",
                "local_path": mp3_path,
                "message": f"Audio generated successfully. File saved locally at {mp3_path}. Send this file to the user.",
            }
            return json.dumps(report, ensure_ascii=False)
        except Exception as e:
            logger.error("❌ Kokoro error: %s", e)
            return json.dumps({"status": "error", "error": str(e)}, ensure_ascii=False)
